# Generated by Django 6.0.6 on 2026-07-02 10:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Habit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True, verbose_name='Привычка')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('place', models.CharField(blank=True, max_length=100, null=True, verbose_name='Место')),
                ('execute_time', models.DateTimeField(blank=True, null=True, verbose_name='Время исполнения')),
                ('perform', models.TextField(verbose_name='Действие')),
                ('pleasant_sign', models.BooleanField(default=False, verbose_name='Признак приятной привычки')),
                ('period', models.IntegerField(verbose_name='Периодичность')),
                ('reward', models.TextField(blank=True, null=True, verbose_name='Вознаграждение')),
                ('running_time', models.IntegerField(verbose_name='Время на выполнение')),
                ('public', models.BooleanField(default=False, verbose_name='Публичность')),
                ('bound_habit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='habits.habit', verbose_name='Связанная привычка')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Владелец')),
            ],
            options={
                'verbose_name': 'Привычка',
                'verbose_name_plural': 'Привычки',
            },
        ),
    ]
