# Generated by Django 6.0.6 on 2026-07-02 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habit',
            name='execute_time',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Время исполнения'),
        ),
        migrations.AlterField(
            model_name='habit',
            name='period',
            field=models.IntegerField(blank=True, null=True, verbose_name='Периодичность'),
        ),
    ]
